{
 "title": "<YOUR DASHBOARD TITLE HERE>",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Current Indoor Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "temperature_indoor", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Outdoor Temperature",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "temperature_outdoor", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    { "expr": "temperature_indoor", "legendFormat": "Indoor Temperature" },
    { "expr": "temperature_outdoor", "legendFormat": "Outdoor Temperature" }
   ]
  },
  {
   "title": "Historic Wind Speed and Direction",
   "type": "spectraphilic-windrose-panel",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "wind_speed", "legendFormat": "__auto" },
    { "expr": "wind_direction", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Maximum Wind Gust (Last 24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "max_over_time(wind_gust[24h])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Current Wind Speed",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wind_speed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "targets": [
    { "expr": "wind_speed", "legendFormat": "Wind Speed" },
    { "expr": "wind_gust", "legendFormat": "Gust Speed" }
   ]
  },
  {
   "title": "National Radar Map",
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 16 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   }
  },
  {
   "title": "Humidity Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "humidity_outdoor", "legendFormat": "Outdoor Humidity" },
    { "expr": "humidity_indoor", "legendFormat": "Indoor Humidity" }
   ]
  },
  {
   "title": "Temperature vs Dew Point",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    { "expr": "temperature_outdoor", "legendFormat": "Temperature" },
    { "expression": "($D * 9/5) + 32", "type": "math" }
   ]
  },
  {
   "title": "Relative Barometric Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "pressurehg" } },
   "targets": [
    { "expr": "barometer_relative_indoor", "legendFormat": "Barometric Pressure" }
   ]
  },
  {
   "title": "Solar Radiation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "targets": [
    { "expr": "solar_radiation", "legendFormat": "Solar Radiation" }
   ]
  },
  {
   "title": "Event/Daily/Hourly Rain",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "lengthin" } },
   "targets": [
    { "expr": "hourly_rain", "legendFormat": "Hourly Rain Total" },
    { "expr": "event_rain", "legendFormat": "Event Rain Total" },
    { "expr": "daily_rain", "legendFormat": "Daily Rain Total" }
   ]
  }
 ]
}